export const ADD_MOVIE = 'ADD_MOVIE';
export const MOVIES_GET_LIST_REQUEST = 'MOVIES_GET_LIST_REQUEST';
export const MOVIES_GET_LIST_RESPONSE = 'MOVIES_GET_LIST_RESPONSE';
export const MOVIES_GET_LIST_FAILURE = 'MOVIES_GET_FAILURE';
